block.10028=torchcolors:black_torch torchcolors:black_wall_torch
block.10028=torchcolors:blue_torch torchcolors:blue_wall_torch
block.10028=torchcolors:brown_torch torchcolors:brown_wall_torch
block.10028=torchcolors:cyan_torch torchcolors:cyan_wall_torch
block.10028=torchcolors:gray_torch torchcolors:gray_wall_torch
block.10028=torchcolors:green_torch torchcolors:green_wall_torch
block.10028=torchcolors:light_blue_torch torchcolors:light_blue_wall_torch
block.10028=torchcolors:light_gray_torch torchcolors:light_gray_wall_torch
block.10028=torchcolors:lime_torch torchcolors:lime_wall_torch
block.10028=torchcolors:magenta_torch torchcolors:magenta_wall_torch
block.10028=torchcolors:orange_torch torchcolors:orange_wall_torch
block.10028=torchcolors:pink_torch torchcolors:pink_wall_torch
block.10028=torchcolors:purple_torch torchcolors:purple_wall_torch
block.10028=torchcolors:red_torch torchcolors:red_wall_torch
block.10028=torchcolors:white_torch torchcolors:white_wall_torch
block.10028=torchcolors:yellow_torch torchcolors:yellow_wall_torch
